server:
  port: 8090
spring:
  mvc:
    # 让404错误抛出异常spring boot默认不会抛出404异常
    throw-exception-if-no-handler-found: true
    static-path-pattern: /uploads/**
  resources:
    add-mappings: false # 禁用静态资源的自动映射，如不禁用，不存在的url将被映射到/**，servlet不有机会抛出异常
    static-locations: file:./data/
  http:
    encoding:
      charset: utf-8
      enabled: true

logging:
  file:
    name: ./logs/SpringBootExample.log

#ServerConfig
appconfig:
  serverId: 0
  datacenterId: 0
  serverName: sxSpringBootExample
  dev: true
  userName:
    - zhangSan
    - lisi
  map:
    key1: value1
    key2: value2

